SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o
    ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.DATETIME IS NOT NULL
    AND i.SEX_UPON_INTAKE LIKE 'Intact%'
    AND (o.SEX_UPON_OUTCOME LIKE 'Spayed%'
        OR o.SEX_UPON_OUTCOME LIKE 'Neutered%'
        )
ORDER BY i.ANIMAL_ID