SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE s
JOIN USER_INFO i
    ON s.USER_ID = i.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER