SELECT FLAVOR
FROM(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS v
    FROM(
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF h
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY j
        ) g
    GROUP BY FLAVOR
) f
ORDER BY v DESC
LIMIT 3