SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM REST_REVIEW r
JOIN MEMBER_PROFILE p
    ON r.MEMBER_ID = p.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM
        (
        SELECT COUNT(*) AS CNT
        FROM REST_REVIEW rrr
        GROUP BY rrr.MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
        ) s)
    )
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT
