SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA d
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) y
    ON YEAR(d.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY YEAR, YEAR_DEV