SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
WHERE MONTH(START_DATE) = 10
    AND c.CAR_TYPE = '세단'
ORDER BY h.CAR_ID DESC