SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n
    ON n.FISH_TYPE = i.FISH_TYPE
WHERE i.LENGTH IS NOT NULL
    AND i.LENGTH = (
        SELECT MAX(fi.LENGTH)
        FROM FISH_INFO fi
        WHERE fi.FISH_TYPE = i.FISH_TYPE
            AND fi.LENGTH IS NOT NULL
        )
ORDER BY ID