SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
JOIN HR_DEPARTMENT d
    ON e.DEPT_ID = d.DEPT_ID
JOIN HR_GRADE g
    ON e.EMP_NO = g.EMP_NO
GROUP BY g.EMP_NO, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
ORDER BY SCORE DESC
LIMIT 1